
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OK
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Admin Desk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\OK\\Downloads\\Agama\\WhatsApp Image 2020-04-07 at 02.27.40.png")); // NOI18N

        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "No KA", "Stasiun Asal", "Stasiun Tujuan", "Tanggal Pemesanan", "Jumlah", "Total"
            }
        ));
        jScrollPane2.setViewportView(tabel2);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No KA", "Nama KA", "Status", "Kedatangan", "Keberangkatan", "Tiba di tujuan", "Sisa Kursi", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jadwal 1", "Jadwal 2", "Jadwal 3", "Jadwal 4", "Jadwal 5", "Jadwal 6" }));

        jButton4.setText("Back to login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(833, 833, 833))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FileReader fr = null;
        tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
        tabel2.setModel(new DefaultTableModel(null,new String[]{"Nama","No KA","Stasiun Asal","Stasiun Tujuan","Tanggal Pemesanan","Jumlah","Total"}));
        try {
            fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\SMT.txt");
        
                  BufferedReader br=new BufferedReader(fr);     
            
                  DefaultTableModel model=(DefaultTableModel)tabel2.getModel();
                  Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        switch(jComboBox1.getSelectedIndex()){
            case 0:tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
                try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T1.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                break;
            case 1:tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
                try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T2.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                break;
            case 2:tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
                try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T3.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                break;
            case 3:tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
                try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T4.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                break;
            case 4:tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
                try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T5.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                break;
            case 5:tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
                try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T6.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                break;
                            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
        tabel2.setModel(new DefaultTableModel(null,new String[]{"Nama","No KA","Stasiun Asal","Stasiun Tujuan","Tanggal Pemesanan","Jumlah","Total"}));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model=(DefaultTableModel)tabel2.getModel();
        try{
        int select=tabel2.getSelectedRow();
        model.removeRow(select);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        File file=new File("SMT.txt");
            FileWriter fw = null;
        try {       
            fw = new FileWriter(file,false);
        } catch (IOException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            PrintWriter pw=new PrintWriter(fw);
            for (int i = 0; i < tabel2.getRowCount(); i++) {
                for (int j = 0; j < tabel2.getColumnCount(); j++) {
                     pw.print(tabel2.getValueAt(i, j)+"/");
                }
                pw.println("");
            }
            pw.close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        login log=new login();
        log.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel1;
    private javax.swing.JTable tabel2;
    // End of variables declaration//GEN-END:variables
}
