
import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OK
 */
public class lanjut extends javax.swing.JFrame {

    /**
     * Creates new form lanjut
     */
    public lanjut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cari = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        reset = new javax.swing.JButton();
        pil1 = new javax.swing.JRadioButton();
        pil2 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jDialog1.setBounds(new java.awt.Rectangle(300, 200, 400, 300));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Uang Tunai :");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Atm Card");

        jButton3.setText("Konfirmasi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Konfirmasi");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(49, 49, 49)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(62, 62, 62)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pilih Rute");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Asal      :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tujuan :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gambir  (GMR)", "Bandung (BD)", "Semarang Tawang (SMT)", "Surabaya Pasar Turi  (SBI)" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gambir  (GMR)", "Bandung (BD)", "Semarang Tawang (SMT)", "Surabaya Pasar Turi  (SBI)" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jSpinner2.setModel(new javax.swing.SpinnerListModel(new String[] {"Januari", "Februari", "Maret ", "April ", "Mei", "Juni", "Juli", "Agustus", "September ", "Oktober", "November", "Desember"}));

        jSpinner3.setModel(new javax.swing.SpinnerListModel(new String[] {"2020", "2021", "2022", "2023"}));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah :");

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama   :");

        update.setText("Cari");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton1.setText("Make Invoice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(171, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update)
                        .addGap(83, 83, 83)
                        .addComponent(jButton1))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(jButton1))
                .addGap(5, 5, 5))
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cari.setText("Bayar");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nama");

        jLabel14.setText(":");

        label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label1.setText("No KA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Stasiun Asal");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Stasiun Tujuan");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tanggal Pemesanan");

        jLabel13.setText(":");

        jLabel11.setText(":");

        jLabel16.setText(":");

        jLabel12.setText(":");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Jumlah");

        jLabel18.setText(":");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1)
                            .addComponent(jLabel15)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(82, 82, 82)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt5)
                            .addComponent(txt6))))
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Invoice");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Total");

        total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(cari))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total))
                    .addComponent(jLabel17)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(total))
                .addGap(9, 9, 9)
                .addComponent(cari)
                .addContainerGap())
        );

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No KA", "Nama KA", "Status", "Kedatangan", "Keberangkatan", "Tiba di tujuan", "Sisa Kursi", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        buttonGroup1.add(pil1);
        pil1.setText("Pilihan 1");

        buttonGroup1.add(pil2);
        pil2.setText("Pilihan 2");

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\OK\\Downloads\\Agama\\WhatsApp Image 2020-04-07 at 02.27.40.png")); // NOI18N

        jButton2.setText("Back to login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pil1)
                                    .addComponent(pil2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(pil1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pil2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset)
                            .addComponent(jButton2))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(0, 9, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
//        jDialog1.setVisible(true);
if(txt1.getText().equals("")){Component frame = null;
        JOptionPane.showMessageDialog(frame, "Input Gagal!!","Inane error",
        JOptionPane.ERROR_MESSAGE);}else{
        File file=new File("SMT.txt");
            FileWriter fw;
        try {       
            fw = new FileWriter(file,true);
        
            PrintWriter pw=new PrintWriter(fw);
            
                pw.print(txt1.getText()+"/"+txt2.getText()+"/"+txt3.getText()+"/"+txt4.getText()+"/"+txt5.getText()+"/"+txt6.getText()+"/"+total.getText()+"/");
                
                pw.println("");
            
            pw.close();
            } catch (IOException ex) {
            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
        }Component frame = null;
JOptionPane.showMessageDialog(frame, "Input Berhasil!!");
txt1.setText("");
txt2.setText("");
txt3.setText("");
txt4.setText("");
txt5.setText("");
txt6.setText("");}
    }//GEN-LAST:event_cariActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        FileReader fr = null;
        tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
        
        switch(jComboBox1.getSelectedIndex()){
            case 0:switch(jComboBox2.getSelectedIndex()){
                case 0:System.out.println("this 1");
                    break;
                case 1:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T1.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 2:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T4.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 3:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T5.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                    }
            break;
            case 1:switch(jComboBox2.getSelectedIndex()){
                case 0:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T1.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 1:System.out.println("this 2");
                    break;
                case 2:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T2.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 3:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T3.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                    }
            break;
            case 2:switch(jComboBox2.getSelectedIndex()){
                case 0:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T4.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 1:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T2.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 2:
                    break;
                case 3:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T6.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                }
            break;
            case 3:switch(jComboBox2.getSelectedIndex()){
                case 0:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T5.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 1:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T3.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 2:try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T6.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;
                case 3:
                    break;
                }
            break;
        }
        
        
            
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt1.setText(nama.getText());
        FileReader fr = null;
        FileReader fr2 = null;
        switch(jComboBox1.getSelectedIndex()){
            case 0:switch(jComboBox2.getSelectedIndex()){
                case 0:break;
                case 1:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T1.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*110000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T1.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*80000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 2:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T4.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*340000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T4.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*525000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 3:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T5.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*450000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T5.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*750000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                }
                break;
            case 1:switch(jComboBox2.getSelectedIndex()){
                case 0:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T1.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*110000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T1.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*80000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 1:break;
                case 2:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T2.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*165000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T2.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*200000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 3:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T3.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*250000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T3.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*460000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                }
                break;
            case 2:switch(jComboBox2.getSelectedIndex()){
                case 0:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T4.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*340000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T4.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*525000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 1:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T2.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*165000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T2.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*200000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 2:break;
                case 3:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T6.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*150000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T6.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*750000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                }
                break;
            case 3:switch(jComboBox2.getSelectedIndex()){
                case 0:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T5.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*450000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T5.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*750000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 1:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T3.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*250000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T3.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*460000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 2:if(pil1.isSelected()){
                            try {        
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T6.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            String isi=br.readLine();
                            String[] note = isi.split("/");
                            txt2.setText(note[0]+" "+note[1]+"|"+note[3]+"|"+note[4]+"|"+note[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*150000;
                            total.setText(": Rp"+ttl);
                            }
            
                            catch (IOException ex) {
                            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        else if(pil2.isSelected()){
                            try {     
                             fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\T6.txt");        
                            BufferedReader br=new BufferedReader(fr);       
                            Object[] lines=br.lines().toArray();
                            String[] row = null;
                            for (int i = 0; i < lines.length; i++) {
                            row=lines[i].toString().split("/");}
                            txt2.setText(row[0]+" "+row[1]+"|"+row[3]+"|"+row[4]+"|"+row[5]);
                            int jml =(int) jSpinner4.getValue();;
                            int ttl=jml*750000;
                            total.setText(": Rp"+ttl);
                         }
            
                         catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
                    break;
                case 3:break;
                }
                break;
        }
        
        
        txt3.setText((String) jComboBox1.getSelectedItem());
        txt4.setText((String) jComboBox2.getSelectedItem()); 
        txt5.setText(jSpinner1.getValue()+"-"+jSpinner2.getValue()+"-"+jSpinner3.getValue());
        txt6.setText( jSpinner4.getValue().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jRadioButton1.isSelected()){
           
            
        }else if(jRadioButton2.isSelected()){
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        FileReader fr = null;
       try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\NewT1.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
       try {
            File file=new File("T1.txt");
            FileWriter fw;
            fw = new FileWriter(file,false);       
            PrintWriter pw=new PrintWriter(fw);
            for (int i = 0; i < tabel1.getRowCount(); i++) {
                for (int j = 0; j < tabel1.getColumnCount(); j++) {
                     pw.print(tabel1.getValueAt(i, j)+"/");
                }
                pw.println("");
            }
            pw.close();
            } catch (IOException ex) {
            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
        }tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
        
        try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\NewT2.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
       try {
            File file=new File("T2.txt");
            FileWriter fw;
            fw = new FileWriter(file,false);       
            PrintWriter pw=new PrintWriter(fw);
            for (int i = 0; i < tabel1.getRowCount(); i++) {
                for (int j = 0; j < tabel1.getColumnCount(); j++) {
                     pw.print(tabel1.getValueAt(i, j)+"/");
                }
                pw.println("");
            }
            pw.close();
            } catch (IOException ex) {
            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
        }tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
        
        try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\NewT3.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
       try {
            File file=new File("T3.txt");
            FileWriter fw;
            fw = new FileWriter(file,false);       
            PrintWriter pw=new PrintWriter(fw);
            for (int i = 0; i < tabel1.getRowCount(); i++) {
                for (int j = 0; j < tabel1.getColumnCount(); j++) {
                     pw.print(tabel1.getValueAt(i, j)+"/");
                }
                pw.println("");
            }
            pw.close();
            } catch (IOException ex) {
            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
        }tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
        
        try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\NewT4.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
       try {
            File file=new File("T4.txt");
            FileWriter fw;
            fw = new FileWriter(file,false);       
            PrintWriter pw=new PrintWriter(fw);
            for (int i = 0; i < tabel1.getRowCount(); i++) {
                for (int j = 0; j < tabel1.getColumnCount(); j++) {
                     pw.print(tabel1.getValueAt(i, j)+"/");
                }
                pw.println("");
            }
            pw.close();
            } catch (IOException ex) {
            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
        }tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
        
        try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\NewT5.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
       try {
            File file=new File("T5.txt");
            FileWriter fw;
            fw = new FileWriter(file,false);       
            PrintWriter pw=new PrintWriter(fw);
            for (int i = 0; i < tabel1.getRowCount(); i++) {
                for (int j = 0; j < tabel1.getColumnCount(); j++) {
                     pw.print(tabel1.getValueAt(i, j)+"/");
                }
                pw.println("");
            }
            pw.close();
            } catch (IOException ex) {
            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
        }tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
        
        try {        
                        fr = new FileReader("D:\\NetBeansProjects\\TugasRancang\\NewT6.txt");
                        BufferedReader br=new BufferedReader(fr);     
            
                        DefaultTableModel model=(DefaultTableModel)tabel1.getModel();
                        Object[] lines=br.lines().toArray();
            
                        for (int i = 0; i < lines.length; i++) {
                          String[] row=lines[i].toString().split("/");
                             model.addRow(row);
                         }
            
                        } catch (IOException ex) {
                        Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
                        }
       try {
            File file=new File("T6.txt");
            FileWriter fw;
            fw = new FileWriter(file,false);       
            PrintWriter pw=new PrintWriter(fw);
            for (int i = 0; i < tabel1.getRowCount(); i++) {
                for (int j = 0; j < tabel1.getColumnCount(); j++) {
                     pw.print(tabel1.getValueAt(i, j)+"/");
                }
                pw.println("");
            }
            pw.close();
            } catch (IOException ex) {
            Logger.getLogger(lanjut.class.getName()).log(Level.SEVERE, null, ex);
        }tabel1.setModel(new DefaultTableModel(null,new String[]{"No KA","Nama KA","Status","Kedatangan","Keberangkatan","Tiba di tujuan","Sisa Kursi","Harga"}));
    }//GEN-LAST:event_resetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login log=new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lanjut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lanjut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lanjut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lanjut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lanjut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton pil1;
    private javax.swing.JRadioButton pil2;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabel1;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
